
[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "never"

[env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "frontend"

[services.source]
repo = "."
rootDirectory = "/frontend-codes"

[services.variables]
NODE_ENV = "production"
PORT = "3000"

[services.networking]
serviceDomain = true
