[variables]
NIXPACKS_PYTHON_VERSION = "3.9"

[phases.setup]
nixPkgs = ["python39", "pip", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT bmad_lms.wsgi:application"

